# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Validate

on:
  push:
    branches: [ "master" ]

jobs:

  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Test
      run: go test -v ./...
      
    - name: Format
      run: if [[ $(go fmt ./...) ]]; then exit -1; fi
    
    - name: Vet
      run: go vet -set-exit-status ./...
      
    - name: setup Lint
      run: go install golang.org/x/lint/golint
      
    - name: Lint
      run: golint -set-exit-status ./...
      
