# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Validate

on:
  pull_request:
  workflow_call:
  workflow_dispatch:
  
jobs:
  format:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - uses: actions/checkout@v3
    - name: Format
      run: export OUTPUT=`go fmt ./...`;if [[ $OUTPUT ]]; then echo $OUTPUT; exit -1; fi
    
  static-security-analysis:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        # Disable detection of weak random number source. This isn't crypto
        args: --exclude G404,G501,G401 ./...
    
  lint:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: setup Lint
      run: go install golang.org/x/lint/golint
    - name: Lint
      run: golint -set_exit_status ./...

  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Test
      run: go test -v ./...
      

      

      
